// <auto-generated />
using System;
using BL.TesteGol.Infra.Data.Airplane.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BL.TesteGol.Infra.Data.Airplane.Migrations
{
    [DbContext(typeof(AirplaneContext))]
    [Migration("20190404162230_0001 - Iniciando Db")]
    partial class _0001IniciandoDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BL.TesteGol.Domain.Airplane.Airplane.Entities.AirplaneModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("QtdPassageiros");

                    b.HasKey("Id");

                    b.ToTable("AirPlanes");
                });
#pragma warning restore 612, 618
        }
    }
}
